instaClone/Smart P2P marketplace/SmartP2PMarketPlace/marketplace/urls.py
from django.conf.urls import url
from django.contrib import admin

from marketapp.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing),
    url(r'^register/$', signup),
    url(r'^login/$',login),
    url(r'^post/$',feed),
    url(r'^feed/$',feed_main),
    url(r'^like/$',like),
    url(r'^upvote/',upvote),
    url(r'^comment/$',comment),
    url(r'^logout/$', logout)
]

instaClone/Smart P2P marketplace/SmartP2PMarketPlace/marketapp/models.py
from __future__ import unicode_literals
import uuid
from django.db import models

import uuid

class UserModel(models.Model):
    name            = models.CharField(max_length=120, null=False)
    email           = models.EmailField()
    username        = models.CharField(max_length=120, unique=True)
    password        = models.CharField(max_length=40)
    created_on      = models.DateTimeField(auto_now_add=True)
    updated_on      = models.DateTimeField(auto_now=True)



class SessionToken(models.Model):
    user            = models.ForeignKey(UserModel)
    session_token   = models.CharField(max_length=120)
    created_on      = models.DateTimeField(auto_now_add=True)
    is_valid        = models.BooleanField(default=True)

    def create_token(self):
        self.session_token = uuid.uuid4()

    

class PostModel(models.Model):
    user            = models.ForeignKey(UserModel)
    image           = models.FileField(upload_to='user_images')
    image_url       = models.CharField(max_length=255)
    caption         = models.CharField(max_length=240)
    created_on      = models.DateTimeField(auto_now_add=True)
    updated_on      = models.DateTimeField(auto_now=True)
    has_liked       = False

    @property
    def like_count(self):
        return len(LikeModel.objects.filter(post=self))

    @property
    def comments(self):
        return CommentModel.objects.filter(post=self).order_by('created_on')

    @property
    def categories(self):
        return CategoryModel.objects.filter(post=self)

class LikeModel(models.Model):
    user            = models.ForeignKey(UserModel)
    post            = models.ForeignKey(PostModel)
    created_on      = models.DateTimeField(auto_now_add=True)
    updated_on      = models.DateTimeField(auto_now=True)

class CommentModel(models.Model):
    user            = models.ForeignKey(UserModel)
    post            = models.ForeignKey(PostModel)
    # likes         = models.ForeignKey(LikeModel)
    comment_text    = models.CharField(max_length=555)
    created_on      = models.DateTimeField(auto_now_add=True)
    updated_on      = models.DateTimeField(auto_now=True)
    has_upvoted     = False

    @property
    def upvote_count(self):
        return len(UpvoteModel.objects.filter(comment=self))

class UpvoteModel(models.Model):
    user            = models.ForeignKey(UserModel)
    comment         = models.ForeignKey(CommentModel)
    created_on      = models.DateTimeField(auto_now_add=True)
    updated_on      = models.DateTimeField(auto_now=True)


class CategoryModel(models.Model):
    post = models.ForeignKey(PostModel)
    category_text = models.CharField(max_length=555)

instaClone/Smart P2P marketplace/SmartP2PMarketPlace/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style media="screen">
  @import url('https://fonts.googleapis.com/css?family=Zilla+Slab');
  @import url('https://fonts.googleapis.com/css?family=Pacifico');
  @import url('https://fonts.googleapis.com/css?family=Permanent+Marker');

  .like-count{
    margin-top: 6px;
    color: #b09b9a;
  }

  .username{
    color: #f4a142;
  }

  #errors{
    background: black;
    border-radius: 5px;
    transition: 2s;
  }
  body , html{
    width:100%;
    height: 100%;
    /*font-family: 'Zilla Slab', serif;*/
    font-family: 'Permanent Marker', cursive;
  }

  #brand-name{
    text-shadow:  0px 1px 0px rgba(0,0,0,0.4),
                  0px 1px 0px rgba(0,0,0,0.3),
                  0px 1px 0px rgba(0,0,0,0.3);
  }

  .fa{
    margin-right: 10px;
  }

  .landing{
    background: url('http://i.imgur.com/e7R6YVQ.jpg') no-repeat center center fixed;
    width: 100%;
    height: 100%;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    font-family: 'Permanent Marker', cursive;
    font-size: 5em;
  }

  .btn,#comment_text {
    font-family: 'Permanent Marker', cursive;
  }

  .navbar, .nav-link{
    font-family: 'Zilla Slab', serif;
    font-size: 15px;

    color: white;
  }

  .navbar-inverse .navbar-nav>li>a {
    color: white;
  }

  .landing-text{
    color: white;
    text-align: center;
    margin: 0 auto;
    display: block;
    margin-top: 17%;
    font-size: 19px;
    text-shadow:  0px 4px 0px rgba(0,0,0,0.4),
                  0px 8px 0px rgba(0,0,0,0.3),
                  0px 9px 0px rgba(0,0,0,0.3);
  }

  h1{
    font-size: 3.5em;
  }

  h2{
    color: #bcf442;
  }

  hr.landing-hr {

    border-color: white;

  }

  a:link {
      color: white;
  }

  /* visited link */
  a:visited {
      color: white;  }

/* mouse over link */
  a:hover {
    color: cyan;
  }

/* selected link */
  a:active {
    color: white; }

  #id_image{
    /*margin-left: 350px;*/
    padding-bottom: 10px;

  }



  h3{
    color: white;
  }

  #create_post{
      display: block;
      margin-top: 10px;
  }

  #id_caption{
      display: block;
  }

  .main{

    width:100%;
    height: 100%;
    overflow: scroll;
    overflow-x: hidden;
    /*background: url('https://static.pexels.com/photos/259962/pexels-photo-259962.jpeg') no-repeat center center fixed;*/
    /*background: url('http://i.imgur.com/oNX5MgY.jpg') no-repeat center center fixed;*/
    background: url('http://i.imgur.com/N4kCdUU.jpg') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    /*font-family: 'Zilla Slab', serif;*/
    color: #040d08;
  }

  .time{
    margin-top: 6px;
    color: #b09b9a;
  }

  .comment_button{
    /*display: none;*/
    margin-top: 3px;
  }

  .created_on {
      color: #b09b9a;
  }

  .btn-upvote{
    font-size: 0.7em;
    color: green;
  }

  .comment-text{
    color: white;
  }

  .tag{

  }

  .container{
    width: 70%;

  }

  input{
    font-family: 'Zilla Slab', serif;
  }

  .navbar-inverse{
    border-width: 0px;
    -webkit-box-shadow: 0px 0px;
    box-shadow: 0px 0px;
    background-color: rgba(0,0,0,0.4);
    background-image: -webkit-gradient(linear, 50.00% 0.00%, 50.00% 100.00%, color-stop( 0% , rgba(0,0,0,0.00)),color-stop( 100% , rgba(0,0,0,0.00)));
    background-image: -webkit-linear-gradient(270deg,rgba(0,0,0,0.00) 0%,rgba(0,0,0,0.00) 100%);
    background-image: linear-gradient(180deg,rgba(0,0,0,0.00) 0%,rgba(0,0,0,0.00) 100%);

  }
  .success{
    text-align: center;
  }

  #login-btn{
      display: block;
      margin: 0 auto;
      padding: 15px;
      align: center;
  }

  .loginForm-container{
    width: 40%;
  }

  #signup,#logIn{
    padding: 10px;
    margin-top: 10px;
    display: block;
    margin: 10px auto;
  }

  hr{
    border-color: grey;
  }

  .field{
    margin-top: 5px;
  }

  footer{
    height: 20px;
    text-align: center;
  }

  .foot p{
    margin-top: 5px;
    font-family: 'Pacifico', cursive;
  }

  .feed{
    margin-top: 0;
    width: 600px;
    height: auto;
    margin: 0 auto;

  }

  .thumbnails{
    width: 100%;
    height: auto;
    padding-bottom: 10%;
  }

  img{
    width: 100%;
    height: auto;
    background-size: cover;
    background-position: center center;
  }

</style>

instaClone/Smart P2P marketplace/SmartP2PMarketPlace/templates/snippets/footer.html
<footer>

    <div class="foot">
            <p>Copyright Sarthak Negi 2017</p>
    </div><!--/.container-fluid -->


</footer>

instaClone/Smart P2P marketplace/SmartP2PMarketPlace/templates/snippets/nav.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <ul class='nav navbar-nav'>
              <li><a class="navbar-brand active" id='brand-name' href="/"><i class="fa fa-camera-retro" aria-hidden="true"></i> P2P MarketPlace</a></li>
            </ul>

          </div>
      <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav navbar-right">
              <li> <a href="/login/" class='nav-link'>Login</a></li>
            </ul>
      </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

instaClone/Smart P2P marketplace/SmartP2PMarketPlace/templates/snippets/scripts.html
<!-- JQuery CDN js -->
<!-- Latest compiled and minified JavaScript -->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<!-- Bootstrap CDN js -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script type="text/javascript">
  var id_caption = document.getElementById('id_caption');
  id_caption.classList.add('form-control');

  $('.comment-button').on('click',function(){
    bootbox.alert({
    message: "The comment was added successfully",
    backdrop: true
  });

});
</script>